digiriseWeb/digiriseWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User, Group

admin.autodiscover()

from rest_framework import generics, permissions, serializers

from oauth2_provider.contrib.rest_framework import TokenHasReadWriteScope, TokenHasScope


# first we define the serializers
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'email', "first_name", "last_name")


class GroupSerializer(serializers.ModelSerializer):
    class Meta:
        model = Group
        fields = ("name",)


# Create the API views
class UserList(generics.ListCreateAPIView):
    permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetails(generics.RetrieveAPIView):
    permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    queryset = User.objects.all()
    serializer_class = UserSerializer


class GroupList(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated, TokenHasScope]
    required_scopes = ['groups']
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


urlpatterns = [
    path('', include('webApp.urls')),
    path('admin/', admin.site.urls),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('users/', UserList.as_view()),
    path('users/<pk>/', UserDetails.as_view()),
    path('groups/', GroupList.as_view()),
]

digiriseWeb/webApp/urls.py
import oauth2_provider.views as oauth2_views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from rest_framework.authtoken import views as token_views
from rest_framework.schemas import get_schema_view

from . import views, infra_views
from .views import swagger_view

admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'document', infra_views.DocumentViewSet)
router.register(r'deployment', infra_views.DeploymentViewSet)
router.register(r'blueprint', infra_views.BlueprintViewSet)
router.register(r'stack', infra_views.StackViewSet)
router.register(r'run_stack', infra_views.RunStackViewSet)

oauth2_endpoint_views = [
    path('authorize/', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    path('token/', oauth2_views.TokenView.as_view(), name="token"),
    path('revoke-token/', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

if settings.DEBUG:
    # OAuth2 Application Management endpoints
    oauth2_endpoint_views += [
        path('applications/', oauth2_views.ApplicationList.as_view(), name="list"),
        path('applications/register/', oauth2_views.ApplicationRegistration.as_view(), name="register"),
        path('applications/<pk>/', oauth2_views.ApplicationDetail.as_view(), name="detail"),
        path('applications/<pk>/delete/', oauth2_views.ApplicationDelete.as_view(), name="delete"),
        path('applications/<pk>/update/', oauth2_views.ApplicationUpdate.as_view(), name="update"),
    ]

    # OAuth2 Token Management endpoints
    oauth2_endpoint_views += [
        path('authorized-tokens/', oauth2_views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
        path('authorized-tokens/<pk>/delete/', oauth2_views.AuthorizedTokenDeleteView.as_view(),
             name="authorized-token-delete"),
    ]

urlpatterns = [
                  path('degirise/', include('django.contrib.auth.urls')),
                  path('api/v1/', include(router.urls), name='router_urls'),
                  path('api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  path('login', auth_views.LoginView.as_view(), name='login'),
                  path('logout', auth_views.LogoutView.as_view(), name='logout'),
                  path('signup', views.signup, name='signup'),
                  path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('upload', views.file_upload, name='upload'),
                  path('', views.index, name='index'),
                  path('about_us', views.about_us, name='about_us'),
                  url(r'upload_files/(?P<filepath>.*)$', views.upload_files_list, name='listfile'),
                  path('delete_all_files', views.delete_all_files, name='delete_all_files'),
                  path('delete_all_deployments', infra_views.delete_all_deployments, name='delete_all_deployments'),
                  path('delete_all_blueprint', infra_views.delete_all_blueprints, name='delete_all_blueprints'),
                  url(r'^oauth/', include('social_django.urls', namespace='social')),  # new
                  # OAuth 2 endpoints:
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('api-token-auth/', token_views.obtain_auth_token)
]
urlpatterns += [
    path('openapi', swagger_view(), name='openapi-schema'),
]

urlpatterns += [
    path('api/docs', TemplateView.as_view(
        template_name='rest_framework/swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
]

digiriseWeb/webApp/models.py
import os
import uuid
from itertools import chain

from django.db import models

STACK_TYPE_CHOICES = [('infra', 'infra'), ('application', 'application')]


class PrintableModel(models.Model):

    def to_dict(self):
        opts = self._meta
        data = {}
        for f in chain(opts.concrete_fields, opts.private_fields):
            data[f.name] = f.value_from_object(self)
        for f in opts.many_to_many:
            data[f.name] = [i.id for i in f.value_from_object(self)]
        return data

    class Meta:
        abstract = True


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='.')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_extension(self):
        name, extension = os.path.splitext(self.document.name)
        return extension

    def get_short_name(self):
        if len(self.document.name) > 10:
            return self.document.name[:9]
        else:
            return self.document.name


class Blueprint(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    blueprint = models.CharField(max_length=255, unique=True)
    blueprint_type = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_short_name(self):
        if len(self.blueprint.name) > 10:
            return self.blueprint.name[:9]
        else:
            return self.blueprint.name


class Deployment(PrintableModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    deployment = models.CharField(max_length=255, unique=True)
    deployment_type = models.CharField(max_length=255, blank=True)
    blueprint = models.ForeignKey(Blueprint, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True)
    deployment_variables = models.JSONField(blank=True, default=dict)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_short_name(self):
        if len(self.deployment.name) > 10:
            return self.deployment.name[:9]
        else:
            return self.deployment.name


class Stack(PrintableModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    deployment = models.ForeignKey(Deployment, on_delete=models.CASCADE)
    stack_name = models.CharField(max_length=255, blank=True)
    stack_type = models.CharField(max_length=255, blank=True, choices=STACK_TYPE_CHOICES)
    code_name = models.CharField(max_length=255, blank=True)
    code = models.JSONField(blank=True, default=dict)
    status = models.CharField(max_length=255, blank=True, default='Not Created')
    created_at = models.DateTimeField(auto_now_add=True)


class RunStack(PrintableModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    deployment = models.ForeignKey(Deployment, on_delete=models.CASCADE)
    blueprint = models.ForeignKey(Blueprint, on_delete=models.CASCADE)
    run_status = models.CharField(max_length=255, blank=True, default='Not Created')
    created_at = models.DateTimeField(auto_now_add=True)

digiriseWeb/webApp/forms.py
from django import forms

from .models import Document, Deployment, Blueprint, Stack


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document',)

class DeploymentForm(forms.ModelForm):
    class Meta:
        model = Deployment
        fields = ('blueprint', 'deployment', 'deployment_type', 'deployment_variables', 'description')


class BlueprintForm(forms.ModelForm):
    class Meta:
        model = Blueprint
        fields = ('blueprint', 'blueprint_type', 'description')


class StackForm(forms.ModelForm):
    class Meta:
        model = Stack
        fields = ('deployment', 'stack_name', 'code_name', 'code', 'status')

digiriseWeb/webApp/views.py
import itertools
from datetime import datetime, timedelta

from oauth2_provider.backends import OAuth2Backend
from oauth2_provider.views.generic import ProtectedResourceView
from django.http import HttpResponse
from azure.storage.blob import BlockBlobService, ContainerPermissions
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.csrf import ensure_csrf_cookie
from rest_framework import viewsets, generics, permissions
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.decorators import permission_classes, renderer_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer

from .digiriseApiViews import ExtView
from .forms import DocumentForm
from .models import Document, Deployment, Stack, Blueprint
from .serializers import DocumentSerializer, DeploymentSerializer, StackSerializer


def get_sas_token():
    blobService = BlockBlobService(account_name=settings.AZURE_ACCOUNT_NAME, account_key=settings.AZURE_ACCOUNT_KEY)
    sas_token = blobService.generate_container_shared_access_signature(settings.MEDIA_CONTAINER,
                                                                       ContainerPermissions.READ,
                                                                       datetime.utcnow() + timedelta(hours=1))
    # print url
    return sas_token


def index(request):
    return render(request, 'webApp/index.html')


def about_us(request):
    return render(request, 'webApp/about_us.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'registration/signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'registration/signup.html', {'form': form})


@ensure_csrf_cookie
def signout(request):
    logout(request)
    return redirect('/')


def email_check(user):
    return user.email.endswith('@example.com')


@login_required(login_url='login')
@permission_required('webApp.add_document')
def file_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            resp = form.save()
            document_name = resp.document
            args = Document.objects.get(document=document_name)
            sas_token = get_sas_token()
            args = {'uploaded_file': args, 'sas_token': sas_token}
            return render(request, 'webApp/upload.html', args)
    else:
        form = DocumentForm()
    return render(request, 'webApp/upload.html', {
        'form': form
    })


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('index')
    template_name = 'registration/signup.html'


class UploadView(generic.CreateView):
    form_class = DocumentForm
    success_url = reverse_lazy('index')
    template_name = 'webApp/model_form_upload.html'


@login_required(login_url='login')
@permission_required('webApp.view_document')
def upload_files_list(request, filepath):
    args = Document.objects.all()
    result = [[v for v in itertools.islice(args, start, start + 5)] for start in range(0, len(args), 5)]
    sas_token = get_sas_token()
    return render(request, 'webApp/upload_list.html', {"doc_list": result, "sas_token": sas_token})


@login_required(login_url='login')
def delete_all_files(request):
    args = Document.objects.all().delete()
    return render(request, 'webApp/delete_all_files.html')


def swagger_view():
    return get_schema_view(
        title="Digirise AB",
        description="Digirise API Documentation",
        version="1.0.0"
    )

digiriseWeb/webApp/templates/webApp/about_us.html
{% extends "base.html" %}

{% block content %}
{% load static %}
       <p class="title">Founders</p>
<div class="tile is-ancestor">
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="subtitle has-text-black">Prateek</p>
            <figure class="image is-128x128">
                <img alt="Prateek"
                     src="static/webApp/Prateek.jpg">
            </figure>
            <p>Prateek is Bachelor in Technology from IIT – Varanasi
                , one of the most reputed university in India. He have a total 18 years of continuous IT experience. He thrive on challenging and responsible role in an organisation. I thrive for great learning opportunities, where he can upgrade himself and advance his knowledge to the next level.</p>

            <p>In all these he have worked in various roles ranging java developer, database administrator, Devops engineer to System Architect in CTO office, follow Industry standard group (ISGs), doing pre-studies and POCs to assist company to take strategic Technological decisions.</p>

            <p>In his current role he mainly focus cutting-edge technologies in Cloud orchestration in Azure, and Openstack based cloud using Terraform, and Ansible. He also act as a Team lead for highly motivated sets of engineer and technically steer the architecture of his IaaC (Infrastructure as a Code)</p>
        </div>
        <div class="tile is-child box">
            <p class="subtitle has-text-black">Shrinkhla</p>
            <figure class="image is-128x128">
                <img alt="Shrinkhla"
                     src="static/webApp/Shrinkhla.jpg">
            </figure>
            <p></p>
        </div>
    </div>
</div>


{% endblock %}

digiriseWeb/webApp/templates/webApp/delete_all_files.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
   Files Deleted
</h1>
{% endblock %}

digiriseWeb/webApp/templates/webApp/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="tile is-ancestor">
    {% if not user.is_authenticated %}
    <div class="tile is-parent is-horizontal">
        <div class="tile is-child box">
            <a class="is-success" href="{% url 'login'%}"><p class="subtitle is-center has-text-black">Not Logged on:
                Please Login</p></a>
        </div>
    </div>
    {% endif %}
</div>

<div class="tile is-ancestor">
    <div class="tile is-parent">

        <div class="tile is-child box">

            <figure class="image">
                <img alt="About us"
                     src="static/webApp/frontPage.png">
            </figure>

            <p>The company focuses on providing consulting, product development in telecom, IoT and IT and related
                activities</p>
        </div>
    </div>

    <div class="tile is-4 is-vertical is-parent">
        <p class="title">Our Offerings</p>
        <div class="tile is-child box">
            <p class="subtitle has-text-black">IoT</p>
            <figure class="image is-128x128">
                <img alt="IoT"
                     src="static/webApp/IOT.png">
            </figure>
        </div>
        <div class="tile is-child box">
            <p class="subtitle has-text-black">Telecom</p>
            <figure class="image is-128x128">
                <img alt="Prateek Srivastava"
                     src="static/webApp/Telecom.png">
            </figure>
        </div>
        <div class="tile is-child box">
            <p class="subtitle has-text-black">DevOps</p>
            <figure class="image is-128x128">
                <img alt="Prateek Srivastava"
                     src="static/webApp/DevOps.png">
            </figure>
        </div>
        <div class="tile is-child box">
            <p class="subtitle has-text-black">Cloud</p>
            <figure class="image is-128x128">
                <img alt="Prateek Srivastava"
                     src="static/webApp/Cloud.png">
            </figure>
        </div>
    </div>
</div>


{% endblock %}

digiriseWeb/webApp/templates/webApp/model_form_upload.html
{% extends 'base.html' %}

{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

<p><a href="{% url 'index' %}">Return to home</a></p>
{% endblock %}

digiriseWeb/webApp/templates/webApp/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    Welcome, {{ name }}!
</h1>
{% endblock %}

digiriseWeb/webApp/templates/webApp/upload.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="field">
        <div class="control">
            <label class="label is-large" for="id_document">Document:</label>
            <input autofocus="" class="input is-large" id="id_document" name="document" placeholder="Your Document"
                   type="file">
        </div>
    </div>
    <button class="button is-block is-info is-large is-fullwidth">Submit</button>
</form>

{% if uploaded_file %}

    <div class="slide">
        <a download href="{{ uploaded_file.document.url }}?{{ sas_token }}">
            {% if uploaded_file.get_extension == '.jpg'  or uploaded_file.get_extension == '.png' %}
            {% load thumbnail %}
            {% thumbnail uploaded_file.document '200x100' padding=True as im %}
            <img src="{{ im.url }}?{{ sas_token }}">
            {% endthumbnail %}
            {% elif uploaded_file.get_extension == '.pdf' %}
            <img src="static/webApp/webApp/icons/file_type_pdf.png">
            {% elif uploaded_file.get_extension == '.log' %}
            <img src="static/webApp/webApp/icons/file_type_txt.png">
            {% elif 'doc' in uploaded_file.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_doc.png">
            {% elif 'xls' in uploaded_file.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_xls.png">
            {% elif 'zip' in uploaded_file.get_extension or rar in uploaded_file.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_zip.png">
            {% elif 'ppt' in uploaded_file.get_extension or 'PPT' in uploaded_file.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_ppt.png">
            {% elif 'htm' in uploaded_file.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_html.png">
            {% else %}
            <img src="static/webApp/webApp/icons/file_type_icons-18.png">
            {% endif %}
        </a>

        <div class="caption" style="bottom:0">
            <p>{{ doc.document}}</p>
        </div>
    </div>
</p>
<p class="has-text-black"><a href="{% url 'listfile' '' %}"><strong>List All Files</strong></a></p>
{% endif %}

<p><a href="{% url 'index' %}">Return to home</a></p>
{% endblock %}

digiriseWeb/webApp/templates/webApp/upload_list.html
{% extends "base.html" %}


<p>ALL FILES:</p>
{% csrf_token %}
{% block content %}
{% load thumbnail %}
<div class="tile is-ancestor">

    {% for doc_set in doc_list %}
         <div class="tile is-parent is-vertical">
         {% for doc in doc_set %}
        <div class="tile is-child box is-flex-wrap-wrap">
       <a class="has-tooltip-bottom" data-tooltip="{{doc.document.name}}" download href="{{ doc.document.url }}?{{ sas_token }}">
            {% load thumbnail %}
            {% if doc.get_extension == '.jpg' or doc.get_extension == '.png' %}
            {% thumbnail doc.document '50x50' padding=True as im %}
             <img src="{{ im.url }}?{{ sas_token }}">
            {% endthumbnail %}
            {% elif doc.get_extension == '.pdf' %}
            <img src="static/webApp/webApp/icons/file_type_pdf.png">
            {% elif doc.get_extension == '.log' %}
            <img src="static/webApp/webApp/icons/file_type_txt.png">
            {% elif 'doc' in doc.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_doc.png">
            {% elif 'xls' in doc.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_xls.png">
            {% elif 'zip' in doc.get_extension or rar in doc.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_zip.png">
            {% elif 'ppt' in doc.get_extension or 'PPT' in doc.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_ppt.png">
            {% elif 'htm' in doc.get_extension %}
            <img src="static/webApp/webApp/icons/file_type_html.png">
            {% else %}
            <img src="static/webApp/webApp/icons/file_type_icons-18.png">
            {% endif %}

        </a>
            <a class="has-tooltip-bottom" data-tooltip="{{doc.document.name}}" download href="{{ doc.document.url }}?{{ sas_token }}">
         <p class="caption is-size-7" style="bottom:0" >
            {{ doc.get_short_name }}
        </p>
            </a>
        </div>
     {% endfor %}
        </div>
    {% endfor %}


</div>
 {% endblock %}